import           BOperations
import           Test.HUnit

results = runTestTT $ test [
        O ~=? bSXor O O,
        X ~=? bSXor O X,
        V 1 N ~=? bSXor O (V 1 N),
        V 2 N ~=? bSXor O (V 2 N),
        V 3 N ~=? bSXor O (V 3 N),
        Bx X (V 1 N) ~=? bSXor O (Bx X (V 1 N)),
        Bx (V 1 N) (V 2 N) ~=? bSXor O (Bx (V 1 N) (V 2 N)),
        Bx (V 3 N) (V 4 N) ~=? bSXor O (Bx (V 3 N) (V 4 N)),
        Bx (V 2 N) (V 4 N) ~=? bSXor O (Bx (V 2 N) (V 4 N)),
        Ba (V 1 N) (V 2 N) ~=? bSXor O (Ba (V 1 N) (V 2 N)),
        Ba (V 3 N) (V 4 N) ~=? bSXor O (Ba (V 3 N) (V 4 N)),
        Ba (V 2 N) (V 4 N) ~=? bSXor O (Ba (V 2 N) (V 4 N)),

        X ~=? bSXor X O,
        O ~=? bSXor X X,
        Bx X (V 1 N) ~=? bSXor X (V 1 N),
        Bx X (V 2 N) ~=? bSXor X (V 2 N),
        Bx X (V 3 N) ~=? bSXor X (V 3 N),
        V 1 N ~=? bSXor X (Bx X (V 1 N)),
        Bx X (Bx (V 1 N) (V 2 N)) ~=? bSXor X (Bx (V 1 N) (V 2 N)),
        Bx X (Bx (V 3 N) (V 4 N)) ~=? bSXor X (Bx (V 3 N) (V 4 N)),
        Bx X (Bx (V 2 N) (V 4 N)) ~=? bSXor X (Bx (V 2 N) (V 4 N)),
        Bx X (Ba (V 1 N) (V 2 N)) ~=? bSXor X (Ba (V 1 N) (V 2 N)),
        Bx X (Ba (V 3 N) (V 4 N)) ~=? bSXor X (Ba (V 3 N) (V 4 N)),
        Bx X (Ba (V 2 N) (V 4 N)) ~=? bSXor X (Ba (V 2 N) (V 4 N)),

        V 1 N ~=? bSXor (V 1 N) O,
        Bx X (V 1 N) ~=? bSXor (V 1 N) X,
        O ~=? bSXor (V 1 N) (V 1 N),
        Bx (V 1 N) (V 2 N) ~=? bSXor (V 1 N) (V 2 N),
        Bx (V 1 N) (V 3 N) ~=? bSXor (V 1 N) (V 3 N),
        X ~=? bSXor (V 1 N) (Bx X (V 1 N)),
        V 2 N ~=? bSXor (V 1 N) (Bx (V 1 N) (V 2 N)),
        Bx (V 1 N) (Bx (V 3 N) (V 4 N)) ~=? bSXor (V 1 N) (Bx (V 3 N) (V 4 N)),
        Bx (V 1 N) (Bx (V 2 N) (V 4 N)) ~=? bSXor (V 1 N) (Bx (V 2 N) (V 4 N)),
        Bx (V 1 N) (Ba (V 1 N) (V 2 N)) ~=? bSXor (V 1 N) (Ba (V 1 N) (V 2 N)),
        Bx (V 1 N) (Ba (V 3 N) (V 4 N)) ~=? bSXor (V 1 N) (Ba (V 3 N) (V 4 N)),
        Bx (V 1 N) (Ba (V 2 N) (V 4 N)) ~=? bSXor (V 1 N) (Ba (V 2 N) (V 4 N)),

        V 2 N ~=? bSXor (V 2 N) O,
        Bx X (V 2 N) ~=? bSXor (V 2 N) X,
        Bx (V 1 N) (V 2 N) ~=? bSXor (V 2 N) (V 1 N),
        O ~=? bSXor (V 2 N) (V 2 N),
        Bx (V 2 N) (V 3 N) ~=? bSXor (V 2 N) (V 3 N),
        Bx X (Bx (V 1 N) (V 2 N)) ~=? bSXor (V 2 N) (Bx X (V 1 N)),
        V 1 N ~=? bSXor (V 2 N) (Bx (V 1 N) (V 2 N)),
        Bx (V 2 N) (Bx (V 3 N) (V 4 N)) ~=? bSXor (V 2 N) (Bx (V 3 N) (V 4 N)),
        V 4 N ~=? bSXor (V 2 N) (Bx (V 2 N) (V 4 N)),
        Bx (V 2 N) (Ba (V 1 N) (V 2 N)) ~=? bSXor (V 2 N) (Ba (V 1 N) (V 2 N)),
        Bx (V 2 N) (Ba (V 3 N) (V 4 N)) ~=? bSXor (V 2 N) (Ba (V 3 N) (V 4 N)),
        Bx (V 2 N) (Ba (V 2 N) (V 4 N)) ~=? bSXor (V 2 N) (Ba (V 2 N) (V 4 N)),

        V 3 N ~=? bSXor (V 3 N) O,
        Bx X (V 3 N) ~=? bSXor (V 3 N) X,
        Bx (V 1 N) (V 3 N) ~=? bSXor (V 3 N) (V 1 N),
        Bx (V 2 N) (V 3 N) ~=? bSXor (V 3 N) (V 2 N),
        O ~=? bSXor (V 3 N) (V 3 N),
        Bx X (Bx (V 1 N) (V 3 N)) ~=? bSXor (V 3 N) (Bx X (V 1 N)),
        Bx (V 1 N) (Bx (V 2 N) (V 3 N)) ~=? bSXor (V 3 N) (Bx (V 1 N) (V 2 N)),
        V 4 N ~=? bSXor (V 3 N) (Bx (V 3 N) (V 4 N)),
        Bx (V 2 N) (Bx (V 3 N) (V 4 N)) ~=? bSXor (V 3 N) (Bx (V 2 N) (V 4 N)),
        Bx (V 3 N) (Ba (V 1 N) (V 2 N)) ~=? bSXor (V 3 N) (Ba (V 1 N) (V 2 N)),
        Bx (V 3 N) (Ba (V 3 N) (V 4 N)) ~=? bSXor (V 3 N) (Ba (V 3 N) (V 4 N)),
        Bx (V 3 N) (Ba (V 2 N) (V 4 N)) ~=? bSXor (V 3 N) (Ba (V 2 N) (V 4 N)),

        Bx X (V 1 N) ~=? bSXor (Bx X (V 1 N)) O,
        V 1 N ~=? bSXor (Bx X (V 1 N)) X,
        X ~=? bSXor (Bx X (V 1 N)) (V 1 N),
        Bx X (Bx (V 1 N) (V 2 N)) ~=? bSXor (Bx X (V 1 N)) (V 2 N),
        Bx X (Bx (V 1 N) (V 3 N)) ~=? bSXor (Bx X (V 1 N)) (V 3 N),
        O ~=? bSXor (Bx X (V 1 N)) (Bx X (V 1 N)),
        Bx X (V 2 N) ~=? bSXor (Bx X (V 1 N)) (Bx (V 1 N) (V 2 N)),
        Bx X (Bx (V 1 N) (Bx (V 3 N) (V 4 N))) ~=? bSXor (Bx X (V 1 N)) (Bx (V 3 N) (V 4 N)),
        Bx X (Bx (V 1 N) (Bx (V 2 N) (V 4 N))) ~=? bSXor (Bx X (V 1 N)) (Bx (V 2 N) (V 4 N)),
        Bx X (Bx (V 1 N) (Ba (V 1 N) (V 2 N))) ~=? bSXor (Bx X (V 1 N)) (Ba (V 1 N) (V 2 N)),
        Bx X (Bx (V 1 N) (Ba (V 3 N) (V 4 N))) ~=? bSXor (Bx X (V 1 N)) (Ba (V 3 N) (V 4 N)),
        Bx X (Bx (V 1 N) (Ba (V 2 N) (V 4 N))) ~=? bSXor (Bx X (V 1 N)) (Ba (V 2 N) (V 4 N)),

        Bx (V 1 N) (V 2 N) ~=? bSXor (Bx (V 1 N) (V 2 N)) O,
        Bx X (Bx (V 1 N) (V 2 N)) ~=? bSXor (Bx (V 1 N) (V 2 N)) X,
        V 2 N ~=? bSXor (Bx (V 1 N) (V 2 N)) (V 1 N),
        V 1 N ~=? bSXor (Bx (V 1 N) (V 2 N)) (V 2 N),
        Bx (V 1 N) (Bx (V 2 N) (V 3 N)) ~=? bSXor (Bx (V 1 N) (V 2 N)) (V 3 N),
        Bx X (V 2 N) ~=? bSXor (Bx (V 1 N) (V 2 N)) (Bx X (V 1 N)),
        O ~=? bSXor (Bx (V 1 N) (V 2 N)) (Bx (V 1 N) (V 2 N)),
        Bx (V 1 N) (Bx (V 2 N) (Bx (V 3 N) (V 4 N))) ~=? bSXor (Bx (V 1 N) (V 2 N)) (Bx (V 3 N) (V 4 N)),
        Bx (V 1 N) (V 4 N) ~=? bSXor (Bx (V 1 N) (V 2 N)) (Bx (V 2 N) (V 4 N)),
        Bx (V 1 N) (Bx (V 2 N) (Ba (V 1 N) (V 2 N))) ~=? bSXor (Bx (V 1 N) (V 2 N)) (Ba (V 1 N) (V 2 N)),
        Bx (V 1 N) (Bx (V 2 N) (Ba (V 3 N) (V 4 N))) ~=? bSXor (Bx (V 1 N) (V 2 N)) (Ba (V 3 N) (V 4 N)),
        Bx (V 1 N) (Bx (V 2 N) (Ba (V 2 N) (V 4 N))) ~=? bSXor (Bx (V 1 N) (V 2 N)) (Ba (V 2 N) (V 4 N)),

        Bx (V 3 N) (V 4 N) ~=? bSXor (Bx (V 3 N) (V 4 N)) O,
        Bx X (Bx (V 3 N) (V 4 N)) ~=? bSXor (Bx (V 3 N) (V 4 N)) X,
        Bx (V 1 N) (Bx (V 3 N) (V 4 N)) ~=? bSXor (Bx (V 3 N) (V 4 N)) (V 1 N),
        Bx (V 2 N) (Bx (V 3 N) (V 4 N)) ~=? bSXor (Bx (V 3 N) (V 4 N)) (V 2 N),
        V 4 N ~=? bSXor (Bx (V 3 N) (V 4 N)) (V 3 N),
        Bx X (Bx (V 1 N) (Bx (V 3 N) (V 4 N))) ~=? bSXor (Bx (V 3 N) (V 4 N)) (Bx X (V 1 N)),
        Bx (V 1 N) (Bx (V 2 N) (Bx (V 3 N) (V 4 N))) ~=? bSXor (Bx (V 3 N) (V 4 N)) (Bx (V 1 N) (V 2 N)),
        O ~=? bSXor (Bx (V 3 N) (V 4 N)) (Bx (V 3 N) (V 4 N)),
        Bx (V 2 N) (V 3 N) ~=? bSXor (Bx (V 3 N) (V 4 N)) (Bx (V 2 N) (V 4 N)),
        Bx (V 3 N) (Bx (V 4 N) (Ba (V 1 N) (V 2 N))) ~=? bSXor (Bx (V 3 N) (V 4 N)) (Ba (V 1 N) (V 2 N)),
        Bx (V 3 N) (Bx (V 4 N) (Ba (V 3 N) (V 4 N))) ~=? bSXor (Bx (V 3 N) (V 4 N)) (Ba (V 3 N) (V 4 N)),
        Bx (V 3 N) (Bx (V 4 N) (Ba (V 2 N) (V 4 N))) ~=? bSXor (Bx (V 3 N) (V 4 N)) (Ba (V 2 N) (V 4 N)),

        Bx (V 2 N) (V 4 N) ~=? bSXor (Bx (V 2 N) (V 4 N)) O,
        Bx X (Bx (V 2 N) (V 4 N)) ~=? bSXor (Bx (V 2 N) (V 4 N)) X,
        Bx (V 1 N) (Bx (V 2 N) (V 4 N)) ~=? bSXor (Bx (V 2 N) (V 4 N)) (V 1 N),
        V 4 N ~=? bSXor (Bx (V 2 N) (V 4 N)) (V 2 N),
        Bx (V 2 N) (Bx (V 3 N) (V 4 N)) ~=? bSXor (Bx (V 2 N) (V 4 N)) (V 3 N),
        Bx X (Bx (V 1 N) (Bx (V 2 N) (V 4 N))) ~=? bSXor (Bx (V 2 N) (V 4 N)) (Bx X (V 1 N)),
        Bx (V 1 N) (V 4 N) ~=? bSXor (Bx (V 2 N) (V 4 N)) (Bx (V 1 N) (V 2 N)),
        Bx (V 2 N) (V 3 N) ~=? bSXor (Bx (V 2 N) (V 4 N)) (Bx (V 3 N) (V 4 N)),
        O ~=? bSXor (Bx (V 2 N) (V 4 N)) (Bx (V 2 N) (V 4 N)),
        Bx (V 2 N) (Bx (V 4 N) (Ba (V 1 N) (V 2 N))) ~=? bSXor (Bx (V 2 N) (V 4 N)) (Ba (V 1 N) (V 2 N)),
        Bx (V 2 N) (Bx (V 4 N) (Ba (V 3 N) (V 4 N))) ~=? bSXor (Bx (V 2 N) (V 4 N)) (Ba (V 3 N) (V 4 N)),
        Bx (V 2 N) (Bx (V 4 N) (Ba (V 2 N) (V 4 N))) ~=? bSXor (Bx (V 2 N) (V 4 N)) (Ba (V 2 N) (V 4 N)),

        Ba (V 1 N) (V 2 N) ~=? bSXor (Ba (V 1 N) (V 2 N)) O,
        Bx X (Ba (V 1 N) (V 2 N)) ~=? bSXor (Ba (V 1 N) (V 2 N)) X,
        Bx (V 1 N) (Ba (V 1 N) (V 2 N)) ~=? bSXor (Ba (V 1 N) (V 2 N)) (V 1 N),
        Bx (V 2 N) (Ba (V 1 N) (V 2 N)) ~=? bSXor (Ba (V 1 N) (V 2 N)) (V 2 N),
        Bx (V 3 N) (Ba (V 1 N) (V 2 N)) ~=? bSXor (Ba (V 1 N) (V 2 N)) (V 3 N),
        Bx X (Bx (V 1 N) (Ba (V 1 N) (V 2 N))) ~=? bSXor (Ba (V 1 N) (V 2 N)) (Bx X (V 1 N)),
        Bx (V 1 N) (Bx (V 2 N) (Ba (V 1 N) (V 2 N))) ~=? bSXor (Ba (V 1 N) (V 2 N)) (Bx (V 1 N) (V 2 N)),
        Bx (V 3 N) (Bx (V 4 N) (Ba (V 1 N) (V 2 N))) ~=? bSXor (Ba (V 1 N) (V 2 N)) (Bx (V 3 N) (V 4 N)),
        Bx (V 2 N) (Bx (V 4 N) (Ba (V 1 N) (V 2 N))) ~=? bSXor (Ba (V 1 N) (V 2 N)) (Bx (V 2 N) (V 4 N)),
        O ~=? bSXor (Ba (V 1 N) (V 2 N)) (Ba (V 1 N) (V 2 N)),
        Bx (Ba (V 1 N) (V 2 N)) (Ba (V 3 N) (V 4 N)) ~=? bSXor (Ba (V 1 N) (V 2 N)) (Ba (V 3 N) (V 4 N)),
        Bx (Ba (V 1 N) (V 2 N)) (Ba (V 2 N) (V 4 N)) ~=? bSXor (Ba (V 1 N) (V 2 N)) (Ba (V 2 N) (V 4 N)),

        Ba (V 3 N) (V 4 N) ~=? bSXor (Ba (V 3 N) (V 4 N)) O,
        Bx X (Ba (V 3 N) (V 4 N)) ~=? bSXor (Ba (V 3 N) (V 4 N)) X,
        Bx (V 1 N) (Ba (V 3 N) (V 4 N)) ~=? bSXor (Ba (V 3 N) (V 4 N)) (V 1 N),
        Bx (V 2 N) (Ba (V 3 N) (V 4 N)) ~=? bSXor (Ba (V 3 N) (V 4 N)) (V 2 N),
        Bx (V 3 N) (Ba (V 3 N) (V 4 N)) ~=? bSXor (Ba (V 3 N) (V 4 N)) (V 3 N),
        Bx X (Bx (V 1 N) (Ba (V 3 N) (V 4 N))) ~=? bSXor (Ba (V 3 N) (V 4 N)) (Bx X (V 1 N)),
        Bx (V 1 N) (Bx (V 2 N) (Ba (V 3 N) (V 4 N))) ~=? bSXor (Ba (V 3 N) (V 4 N)) (Bx (V 1 N) (V 2 N)),
        Bx (V 3 N) (Bx (V 4 N) (Ba (V 3 N) (V 4 N))) ~=? bSXor (Ba (V 3 N) (V 4 N)) (Bx (V 3 N) (V 4 N)),
        Bx (V 2 N) (Bx (V 4 N) (Ba (V 3 N) (V 4 N))) ~=? bSXor (Ba (V 3 N) (V 4 N)) (Bx (V 2 N) (V 4 N)),
        Bx (Ba (V 1 N) (V 2 N)) (Ba (V 3 N) (V 4 N)) ~=? bSXor (Ba (V 3 N) (V 4 N)) (Ba (V 1 N) (V 2 N)),
        O ~=? bSXor (Ba (V 3 N) (V 4 N)) (Ba (V 3 N) (V 4 N)),
        Bx (Ba (V 2 N) (V 4 N)) (Ba (V 3 N) (V 4 N)) ~=? bSXor (Ba (V 3 N) (V 4 N)) (Ba (V 2 N) (V 4 N)),

        Ba (V 2 N) (V 4 N) ~=? bSXor (Ba (V 2 N) (V 4 N)) O,
        Bx X (Ba (V 2 N) (V 4 N)) ~=? bSXor (Ba (V 2 N) (V 4 N)) X,
        Bx (V 1 N) (Ba (V 2 N) (V 4 N)) ~=? bSXor (Ba (V 2 N) (V 4 N)) (V 1 N),
        Bx (V 2 N) (Ba (V 2 N) (V 4 N)) ~=? bSXor (Ba (V 2 N) (V 4 N)) (V 2 N),
        Bx (V 3 N) (Ba (V 2 N) (V 4 N)) ~=? bSXor (Ba (V 2 N) (V 4 N)) (V 3 N),
        Bx X (Bx (V 1 N) (Ba (V 2 N) (V 4 N))) ~=? bSXor (Ba (V 2 N) (V 4 N)) (Bx X (V 1 N)),
        Bx (V 1 N) (Bx (V 2 N) (Ba (V 2 N) (V 4 N))) ~=? bSXor (Ba (V 2 N) (V 4 N)) (Bx (V 1 N) (V 2 N)),
        Bx (V 3 N) (Bx (V 4 N) (Ba (V 2 N) (V 4 N))) ~=? bSXor (Ba (V 2 N) (V 4 N)) (Bx (V 3 N) (V 4 N)),
        Bx (V 2 N) (Bx (V 4 N) (Ba (V 2 N) (V 4 N))) ~=? bSXor (Ba (V 2 N) (V 4 N)) (Bx (V 2 N) (V 4 N)),
        Bx (Ba (V 1 N) (V 2 N)) (Ba (V 2 N) (V 4 N)) ~=? bSXor (Ba (V 2 N) (V 4 N)) (Ba (V 1 N) (V 2 N)),
        Bx (Ba (V 2 N) (V 4 N)) (Ba (V 3 N) (V 4 N)) ~=? bSXor (Ba (V 2 N) (V 4 N)) (Ba (V 3 N) (V 4 N)),
        O ~=? bSXor (Ba (V 2 N) (V 4 N)) (Ba (V 2 N) (V 4 N))
    ]

