import           BOperations
import           Test.HUnit

results = runTestTT $ test [
        O ~=? bSXor O O,
        X ~=? bSXor O X,
        V 1 ~=? bSXor O (V 1),
        V 2 ~=? bSXor O (V 2),
        V 3 ~=? bSXor O (V 3),
        Bx X (V 1) ~=? bSXor O (Bx X (V 1)),
        Bx (V 1) (V 2) ~=? bSXor O (Bx (V 1) (V 2)),
        Bx (V 3) (V 4) ~=? bSXor O (Bx (V 3) (V 4)),
        Bx (V 2) (V 4) ~=? bSXor O (Bx (V 2) (V 4)),
        Ba (V 1) (V 2) ~=? bSXor O (Ba (V 1) (V 2)),
        Ba (V 3) (V 4) ~=? bSXor O (Ba (V 3) (V 4)),
        Ba (V 2) (V 4) ~=? bSXor O (Ba (V 2) (V 4)),

        X ~=? bSXor X O,
        O ~=? bSXor X X,
        Bx X (V 1) ~=? bSXor X (V 1),
        Bx X (V 2) ~=? bSXor X (V 2),
        Bx X (V 3) ~=? bSXor X (V 3),
        V 1 ~=? bSXor X (Bx X (V 1)),
        Bx X (Bx (V 1) (V 2)) ~=? bSXor X (Bx (V 1) (V 2)),
        Bx X (Bx (V 3) (V 4)) ~=? bSXor X (Bx (V 3) (V 4)),
        Bx X (Bx (V 2) (V 4)) ~=? bSXor X (Bx (V 2) (V 4)),
        Bx X (Ba (V 1) (V 2)) ~=? bSXor X (Ba (V 1) (V 2)),
        Bx X (Ba (V 3) (V 4)) ~=? bSXor X (Ba (V 3) (V 4)),
        Bx X (Ba (V 2) (V 4)) ~=? bSXor X (Ba (V 2) (V 4)),

        V 1 ~=? bSXor (V 1) O,
        Bx X (V 1) ~=? bSXor (V 1) X,
        O ~=? bSXor (V 1) (V 1),
        Bx (V 1) (V 2) ~=? bSXor (V 1) (V 2),
        Bx (V 1) (V 3) ~=? bSXor (V 1) (V 3),
        X ~=? bSXor (V 1) (Bx X (V 1)),
        V 2 ~=? bSXor (V 1) (Bx (V 1) (V 2)),
        Bx (V 1) (Bx (V 3) (V 4)) ~=? bSXor (V 1) (Bx (V 3) (V 4)),
        Bx (V 1) (Bx (V 2) (V 4)) ~=? bSXor (V 1) (Bx (V 2) (V 4)),
        Bx (V 1) (Ba (V 1) (V 2)) ~=? bSXor (V 1) (Ba (V 1) (V 2)),
        Bx (V 1) (Ba (V 3) (V 4)) ~=? bSXor (V 1) (Ba (V 3) (V 4)),
        Bx (V 1) (Ba (V 2) (V 4)) ~=? bSXor (V 1) (Ba (V 2) (V 4)),

        V 2 ~=? bSXor (V 2) O,
        Bx X (V 2) ~=? bSXor (V 2) X,
        Bx (V 1) (V 2) ~=? bSXor (V 2) (V 1),
        O ~=? bSXor (V 2) (V 2),
        Bx (V 2) (V 3) ~=? bSXor (V 2) (V 3),
        Bx X (Bx (V 1) (V 2)) ~=? bSXor (V 2) (Bx X (V 1)),
        V 1 ~=? bSXor (V 2) (Bx (V 1) (V 2)),
        Bx (V 2) (Bx (V 3) (V 4)) ~=? bSXor (V 2) (Bx (V 3) (V 4)),
        V 4 ~=? bSXor (V 2) (Bx (V 2) (V 4)),
        Bx (V 2) (Ba (V 1) (V 2)) ~=? bSXor (V 2) (Ba (V 1) (V 2)),
        Bx (V 2) (Ba (V 3) (V 4)) ~=? bSXor (V 2) (Ba (V 3) (V 4)),
        Bx (V 2) (Ba (V 2) (V 4)) ~=? bSXor (V 2) (Ba (V 2) (V 4)),

        V 3 ~=? bSXor (V 3) O,
        Bx X (V 3) ~=? bSXor (V 3) X,
        Bx (V 1) (V 3) ~=? bSXor (V 3) (V 1),
        Bx (V 2) (V 3) ~=? bSXor (V 3) (V 2),
        O ~=? bSXor (V 3) (V 3),
        Bx X (Bx (V 1) (V 3)) ~=? bSXor (V 3) (Bx X (V 1)),
        Bx (V 1) (Bx (V 2) (V 3)) ~=? bSXor (V 3) (Bx (V 1) (V 2)),
        V 4 ~=? bSXor (V 3) (Bx (V 3) (V 4)),
        Bx (V 2) (Bx (V 3) (V 4)) ~=? bSXor (V 3) (Bx (V 2) (V 4)),
        Bx (V 3) (Ba (V 1) (V 2)) ~=? bSXor (V 3) (Ba (V 1) (V 2)),
        Bx (V 3) (Ba (V 3) (V 4)) ~=? bSXor (V 3) (Ba (V 3) (V 4)),
        Bx (V 3) (Ba (V 2) (V 4)) ~=? bSXor (V 3) (Ba (V 2) (V 4)),

        Bx X (V 1) ~=? bSXor (Bx X (V 1)) O,
        V 1 ~=? bSXor (Bx X (V 1)) X,
        X ~=? bSXor (Bx X (V 1)) (V 1),
        Bx X (Bx (V 1) (V 2)) ~=? bSXor (Bx X (V 1)) (V 2),
        Bx X (Bx (V 1) (V 3)) ~=? bSXor (Bx X (V 1)) (V 3),
        O ~=? bSXor (Bx X (V 1)) (Bx X (V 1)),
        Bx X (V 2) ~=? bSXor (Bx X (V 1)) (Bx (V 1) (V 2)),
        Bx X (Bx (V 1) (Bx (V 3) (V 4))) ~=? bSXor (Bx X (V 1)) (Bx (V 3) (V 4)),
        Bx X (Bx (V 1) (Bx (V 2) (V 4))) ~=? bSXor (Bx X (V 1)) (Bx (V 2) (V 4)),
        Bx X (Bx (V 1) (Ba (V 1) (V 2))) ~=? bSXor (Bx X (V 1)) (Ba (V 1) (V 2)),
        Bx X (Bx (V 1) (Ba (V 3) (V 4))) ~=? bSXor (Bx X (V 1)) (Ba (V 3) (V 4)),
        Bx X (Bx (V 1) (Ba (V 2) (V 4))) ~=? bSXor (Bx X (V 1)) (Ba (V 2) (V 4)),

        Bx (V 1) (V 2) ~=? bSXor (Bx (V 1) (V 2)) O,
        Bx X (Bx (V 1) (V 2)) ~=? bSXor (Bx (V 1) (V 2)) X,
        V 2 ~=? bSXor (Bx (V 1) (V 2)) (V 1),
        V 1 ~=? bSXor (Bx (V 1) (V 2)) (V 2),
        Bx (V 1) (Bx (V 2) (V 3)) ~=? bSXor (Bx (V 1) (V 2)) (V 3),
        Bx X (V 2) ~=? bSXor (Bx (V 1) (V 2)) (Bx X (V 1)),
        O ~=? bSXor (Bx (V 1) (V 2)) (Bx (V 1) (V 2)),
        Bx (V 1) (Bx (V 2) (Bx (V 3) (V 4))) ~=? bSXor (Bx (V 1) (V 2)) (Bx (V 3) (V 4)),
        Bx (V 1) (V 4) ~=? bSXor (Bx (V 1) (V 2)) (Bx (V 2) (V 4)),
        Bx (V 1) (Bx (V 2) (Ba (V 1) (V 2))) ~=? bSXor (Bx (V 1) (V 2)) (Ba (V 1) (V 2)),
        Bx (V 1) (Bx (V 2) (Ba (V 3) (V 4))) ~=? bSXor (Bx (V 1) (V 2)) (Ba (V 3) (V 4)),
        Bx (V 1) (Bx (V 2) (Ba (V 2) (V 4))) ~=? bSXor (Bx (V 1) (V 2)) (Ba (V 2) (V 4)),

        Bx (V 3) (V 4) ~=? bSXor (Bx (V 3) (V 4)) O,
        Bx X (Bx (V 3) (V 4)) ~=? bSXor (Bx (V 3) (V 4)) X,
        Bx (V 1) (Bx (V 3) (V 4)) ~=? bSXor (Bx (V 3) (V 4)) (V 1),
        Bx (V 2) (Bx (V 3) (V 4)) ~=? bSXor (Bx (V 3) (V 4)) (V 2),
        V 4 ~=? bSXor (Bx (V 3) (V 4)) (V 3),
        Bx X (Bx (V 1) (Bx (V 3) (V 4))) ~=? bSXor (Bx (V 3) (V 4)) (Bx X (V 1)),
        Bx (V 1) (Bx (V 2) (Bx (V 3) (V 4))) ~=? bSXor (Bx (V 3) (V 4)) (Bx (V 1) (V 2)),
        O ~=? bSXor (Bx (V 3) (V 4)) (Bx (V 3) (V 4)),
        Bx (V 2) (V 3) ~=? bSXor (Bx (V 3) (V 4)) (Bx (V 2) (V 4)),
        Bx (V 3) (Bx (V 4) (Ba (V 1) (V 2))) ~=? bSXor (Bx (V 3) (V 4)) (Ba (V 1) (V 2)),
        Bx (V 3) (Bx (V 4) (Ba (V 3) (V 4))) ~=? bSXor (Bx (V 3) (V 4)) (Ba (V 3) (V 4)),
        Bx (V 3) (Bx (V 4) (Ba (V 2) (V 4))) ~=? bSXor (Bx (V 3) (V 4)) (Ba (V 2) (V 4)),

        Bx (V 2) (V 4) ~=? bSXor (Bx (V 2) (V 4)) O,
        Bx X (Bx (V 2) (V 4)) ~=? bSXor (Bx (V 2) (V 4)) X,
        Bx (V 1) (Bx (V 2) (V 4)) ~=? bSXor (Bx (V 2) (V 4)) (V 1),
        V 4 ~=? bSXor (Bx (V 2) (V 4)) (V 2),
        Bx (V 2) (Bx (V 3) (V 4)) ~=? bSXor (Bx (V 2) (V 4)) (V 3),
        Bx X (Bx (V 1) (Bx (V 2) (V 4))) ~=? bSXor (Bx (V 2) (V 4)) (Bx X (V 1)),
        Bx (V 1) (V 4) ~=? bSXor (Bx (V 2) (V 4)) (Bx (V 1) (V 2)),
        Bx (V 2) (V 3) ~=? bSXor (Bx (V 2) (V 4)) (Bx (V 3) (V 4)),
        O ~=? bSXor (Bx (V 2) (V 4)) (Bx (V 2) (V 4)),
        Bx (V 2) (Bx (V 4) (Ba (V 1) (V 2))) ~=? bSXor (Bx (V 2) (V 4)) (Ba (V 1) (V 2)),
        Bx (V 2) (Bx (V 4) (Ba (V 3) (V 4))) ~=? bSXor (Bx (V 2) (V 4)) (Ba (V 3) (V 4)),
        Bx (V 2) (Bx (V 4) (Ba (V 2) (V 4))) ~=? bSXor (Bx (V 2) (V 4)) (Ba (V 2) (V 4)),

        Ba (V 1) (V 2) ~=? bSXor (Ba (V 1) (V 2)) O,
        Bx X (Ba (V 1) (V 2)) ~=? bSXor (Ba (V 1) (V 2)) X,
        Bx (V 1) (Ba (V 1) (V 2)) ~=? bSXor (Ba (V 1) (V 2)) (V 1),
        Bx (V 2) (Ba (V 1) (V 2)) ~=? bSXor (Ba (V 1) (V 2)) (V 2),
        Bx (V 3) (Ba (V 1) (V 2)) ~=? bSXor (Ba (V 1) (V 2)) (V 3),
        Bx X (Bx (V 1) (Ba (V 1) (V 2))) ~=? bSXor (Ba (V 1) (V 2)) (Bx X (V 1)),
        Bx (V 1) (Bx (V 2) (Ba (V 1) (V 2))) ~=? bSXor (Ba (V 1) (V 2)) (Bx (V 1) (V 2)),
        Bx (V 3) (Bx (V 4) (Ba (V 1) (V 2))) ~=? bSXor (Ba (V 1) (V 2)) (Bx (V 3) (V 4)),
        Bx (V 2) (Bx (V 4) (Ba (V 1) (V 2))) ~=? bSXor (Ba (V 1) (V 2)) (Bx (V 2) (V 4)),
        O ~=? bSXor (Ba (V 1) (V 2)) (Ba (V 1) (V 2)),
        Bx (Ba (V 1) (V 2)) (Ba (V 3) (V 4)) ~=? bSXor (Ba (V 1) (V 2)) (Ba (V 3) (V 4)),
        Bx (Ba (V 1) (V 2)) (Ba (V 2) (V 4)) ~=? bSXor (Ba (V 1) (V 2)) (Ba (V 2) (V 4)),

        Ba (V 3) (V 4) ~=? bSXor (Ba (V 3) (V 4)) O,
        Bx X (Ba (V 3) (V 4)) ~=? bSXor (Ba (V 3) (V 4)) X,
        Bx (V 1) (Ba (V 3) (V 4)) ~=? bSXor (Ba (V 3) (V 4)) (V 1),
        Bx (V 2) (Ba (V 3) (V 4)) ~=? bSXor (Ba (V 3) (V 4)) (V 2),
        Bx (V 3) (Ba (V 3) (V 4)) ~=? bSXor (Ba (V 3) (V 4)) (V 3),
        Bx X (Bx (V 1) (Ba (V 3) (V 4))) ~=? bSXor (Ba (V 3) (V 4)) (Bx X (V 1)),
        Bx (V 1) (Bx (V 2) (Ba (V 3) (V 4))) ~=? bSXor (Ba (V 3) (V 4)) (Bx (V 1) (V 2)),
        Bx (V 3) (Bx (V 4) (Ba (V 3) (V 4))) ~=? bSXor (Ba (V 3) (V 4)) (Bx (V 3) (V 4)),
        Bx (V 2) (Bx (V 4) (Ba (V 3) (V 4))) ~=? bSXor (Ba (V 3) (V 4)) (Bx (V 2) (V 4)),
        Bx (Ba (V 1) (V 2)) (Ba (V 3) (V 4)) ~=? bSXor (Ba (V 3) (V 4)) (Ba (V 1) (V 2)),
        O ~=? bSXor (Ba (V 3) (V 4)) (Ba (V 3) (V 4)),
        Bx (Ba (V 2) (V 4)) (Ba (V 3) (V 4)) ~=? bSXor (Ba (V 3) (V 4)) (Ba (V 2) (V 4)),

        Ba (V 2) (V 4) ~=? bSXor (Ba (V 2) (V 4)) O,
        Bx X (Ba (V 2) (V 4)) ~=? bSXor (Ba (V 2) (V 4)) X,
        Bx (V 1) (Ba (V 2) (V 4)) ~=? bSXor (Ba (V 2) (V 4)) (V 1),
        Bx (V 2) (Ba (V 2) (V 4)) ~=? bSXor (Ba (V 2) (V 4)) (V 2),
        Bx (V 3) (Ba (V 2) (V 4)) ~=? bSXor (Ba (V 2) (V 4)) (V 3),
        Bx X (Bx (V 1) (Ba (V 2) (V 4))) ~=? bSXor (Ba (V 2) (V 4)) (Bx X (V 1)),
        Bx (V 1) (Bx (V 2) (Ba (V 2) (V 4))) ~=? bSXor (Ba (V 2) (V 4)) (Bx (V 1) (V 2)),
        Bx (V 3) (Bx (V 4) (Ba (V 2) (V 4))) ~=? bSXor (Ba (V 2) (V 4)) (Bx (V 3) (V 4)),
        Bx (V 2) (Bx (V 4) (Ba (V 2) (V 4))) ~=? bSXor (Ba (V 2) (V 4)) (Bx (V 2) (V 4)),
        Bx (Ba (V 1) (V 2)) (Ba (V 2) (V 4)) ~=? bSXor (Ba (V 2) (V 4)) (Ba (V 1) (V 2)),
        Bx (Ba (V 2) (V 4)) (Ba (V 3) (V 4)) ~=? bSXor (Ba (V 2) (V 4)) (Ba (V 3) (V 4)),
        O ~=? bSXor (Ba (V 2) (V 4)) (Ba (V 2) (V 4))
    ]

